### PR TITLE
Main

### PR DESCRIPTION
**Pull request by reinasun**

### CODE REVIEW

**Comment by dylviz** [comment]
Hi @reinasun, It looks like this PR has a build error. Let me know if there's something causing issue and we can try to figure it out

**Comment by dylviz** [comment]
Actually, I see that this is a problem with the vercel config. I can approve this but are you sure a blank readme is better than instructions to get running?

**Comment by reinasun** [comment]
I was testing to make sure I could commit. I fixed it. I finished the About us page and added the header/footer.

**Comment by dylviz** [comment]
I'm going to close this PR and allow you to reopen the new one with the changes you mentioned

**Comment by reinasun** [comment]
the changes should be committed. lmk if you have any issues

**Comment by dylviz** [comment]
> the changes should be committed. lmk if you have any issues

They might not be pushed. There's only one commit in this PR (8c2ae682f5fb78f803dc9b6170ee0d225ebe27c5)

**Pull request closed without merging**
